### ISSUE TITLE
Διαγραφή test αιτήσεων από form.io και Βonita

### ISSUE THREAD

**Issue by mfassea** [OBI-GRIPO/e-filing#10]
Πρόκειται για bug του bonita το οποίο δεν έχουμε καταφέρει να διαγνώσουμε

**Comment by sl45sms** [comment]
Αφορά το μαζικό σβήσιμο παλαιών δοκιμαστικών εγγραφών. Εναλλακτικά, μιας και δεν θα ξαναυπάρξει απαίτηση για μαζικό σβήσιμο μπορούν να διαγραφούν μια προς μια.  
**Σε καθε περιπτωση δεν δημιουργειται κανενα προβλημα στην λειτουργια του συστηματος.**

**Comment by mfassea** [comment]
Η διαγραφή ορισμένων αιτήσεων στάθηκε αδύνατη από το περιβάλλον τυ ΟΒΙ είτε μία προς μία είτε μαζικά. Ορισμένες εγγραφές διαγράφηκαν remotely από τον ΠΣ πράγμα που αποδεικνύει ότι το προβλημα  χρήζει περαιτέρω διερεύνησης.

**Comment by mfassea** [comment]
Από τον Π.Σκ. έχει βρεθεί ακριβώς το bug και θα δρομολογηθεί η επίλυσή του μόλις επιτρέψουν τα επιο επείγοντα θέματα

**Comment by mfassea** [comment]
έχει κλείσει. Οι αιτήσεις μπορούν να διαγραφούν μία προς μία
